// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl4zyHCpiK1wQL2bCqbx9J1v2pJ8ZziXg',
    appId: '1:57617410456:web:bc69d70f989ac772cf23ed',
    messagingSenderId: '57617410456',
    projectId: 'actividad-a6484',
    authDomain: 'actividad-a6484.firebaseapp.com',
    storageBucket: 'actividad-a6484.appspot.com',
    measurementId: 'G-SGC6XW7CBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5XvqmMLVt738fdtOp9TvGBUQThhF-zZQ',
    appId: '1:57617410456:android:11513e18c545f89bcf23ed',
    messagingSenderId: '57617410456',
    projectId: 'actividad-a6484',
    storageBucket: 'actividad-a6484.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8_V2_RUiz-7Fz22zs3dc6KYJn50yhi0U',
    appId: '1:57617410456:ios:892fabee86800c57cf23ed',
    messagingSenderId: '57617410456',
    projectId: 'actividad-a6484',
    storageBucket: 'actividad-a6484.appspot.com',
    iosClientId: '57617410456-ij3643krjd6174nia6ducihiv57osr6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.actividad',
  );
}
